schema_version: 1

context:
  version: "0.24.0"

package:
  name: beetcamp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/beetcamp/beetcamp-${{ version }}.tar.gz
  sha256: e3edcfd79ca7ccf8cc6c8a64aef2b7dbefab20d319bd72e42b048f59863e12a6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - beetcamp = beetsplug.bandcamp:main

requirements:
  host:
    - python ${{ python_min }}*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - beets >=1.5
    - pycountry >=20.7.3
    - httpx >=0.27.0
    - packaging >=24.0

tests:
  - python:
      imports:
        - beetsplug.bandcamp
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}*
    script:
      - beetcamp --help

about:
  summary: Bandcamp autotagger source for beets (http://beets.io).
  license: GPL-2.0-only
  license_file: LICENSE
  homepage: https://github.com/snejus/beetcamp

extra:
  recipe-maintainers:
    - HeavyTony2
